fmd_booking_management:
    resource: "@FmdBookingManagementBundle/Resources/config/routing.yml"
    prefix:   /

fmd_personne:
    resource: "@FmdPersonneBundle/Resources/config/routing.yml"
    prefix:   /personne

app:
    resource: '@AppBundle/Controller/'
    type: annotation
