oc_rerevisions_homepage:
    path:     /
    defaults: { _controller: OCRerevisionsBundle:Default:index }

oc_rerevisions_rerevisions :
    path :    /rerevisions/{annee}/{fichier}.{_format}
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:rerevisions
        annee : 2018
        fichier : sansNom
        _format : html
    requirements :
        annee : \d{1,4}
        _format : jpg|jpeg|png|gif|html|xml

oc_rerevisions_decompose :
    path :    /decompose
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:decompose

oc_rerevisions_reponseRapide :
    path :    /reponseRapide
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:reponseRapide

oc_rerevisions_redirection :
    path :    /redirection
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:redirection

oc_rerevisions_session :
    path :    /session
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:session

oc_rerevisions_flashSession :
    path :    /flashSession
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:flashSession

oc_rerevisions_mail :
    path :    /mail
    defaults :
        _controller : OCRerevisionsBundle:Rerevisions:mail