<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqf6sfj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqf6sfj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSqf6sfj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSqf6sfj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSqf6sfj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Sqf6sfj',
    'container.build_id' => '01f03095',
    'container.build_time' => 1530704199,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqf6sfj');
