<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYvmafqd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYvmafqd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYvmafqd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYvmafqd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYvmafqd\appProdProjectContainer(array(
    'container.build_hash' => 'Yvmafqd',
    'container.build_id' => 'e966828f',
    'container.build_time' => 1532366900,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYvmafqd');
