<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT1oblrq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT1oblrq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT1oblrq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT1oblrq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT1oblrq\appProdProjectContainer(array(
    'container.build_hash' => 'T1oblrq',
    'container.build_id' => '264831d1',
    'container.build_time' => 1545322512,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT1oblrq');
