<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5zsnf6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5zsnf6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM5zsnf6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM5zsnf6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM5zsnf6\appProdProjectContainer(array(
    'container.build_hash' => 'M5zsnf6',
    'container.build_id' => '36f49f35',
    'container.build_time' => 1530187892,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5zsnf6');
