<?php

namespace Fmd\BookingManagementBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function idReservationViaMail($mail)
    {
        //$repository = $this->getDoctrine()->getManager()->getRepository('FmdBookingManagementBundle:Reservation');
        $query = $this->_em->createQuery('SELECT r.id FROM FmdBookingManagementBundle:Reservation r WHERE r.mail = :mail');
        $query->setParameter('mail', $mail);

        return $query->getResult();
    }*/
    
    public function getReservationsViaMail($mail)
    {
        $query = $this->_em->createQuery("SELECT r FROM FmdBookingManagementBundle:Reservation r WHERE r.mail = :mail AND r.dateReservation >= CURRENT_DATE() ORDER BY r.dateReservation ASC");
        $query->setParameter('mail', $mail);

        return $query->getResult();
    }
}
