<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbmabti\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbmabti/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWbmabti.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWbmabti\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerWbmabti\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Wbmabti',
    'container.build_id' => 'd93c0c1b',
    'container.build_time' => 1530707165,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbmabti');
