<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC98yvyo\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC98yvyo/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC98yvyo.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC98yvyo\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerC98yvyo\appTestDebugProjectContainer(array(
    'container.build_hash' => 'C98yvyo',
    'container.build_id' => '1d9b59ea',
    'container.build_time' => 1529343818,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerC98yvyo');
