<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOc0wgpm\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOc0wgpm/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOc0wgpm.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOc0wgpm\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerOc0wgpm\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Oc0wgpm',
    'container.build_id' => 'ff0379f3',
    'container.build_time' => 1531156575,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOc0wgpm');
