<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrtf7te\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrtf7te/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJrtf7te.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJrtf7te\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerJrtf7te\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Jrtf7te',
    'container.build_id' => '4818f4d9',
    'container.build_time' => 1529948236,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJrtf7te');
