<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXaxiosy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXaxiosy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXaxiosy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXaxiosy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXaxiosy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xaxiosy',
    'container.build_id' => '90d8a021',
    'container.build_time' => 1530723792,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXaxiosy');
