<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrdunek\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrdunek/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUrdunek.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUrdunek\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUrdunek\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Urdunek',
    'container.build_id' => '3bd15617',
    'container.build_time' => 1529948075,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrdunek');
